ALTER TABLE company ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE company ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(500);
ALTER TABLE company ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(500);
ALTER TABLE company ADD COLUMN IF NOT EXISTS website_url VARCHAR(500);
ALTER TABLE company ADD COLUMN IF NOT EXISTS tiktok_url VARCHAR(500);

ALTER TABLE company ADD COLUMN IF NOT EXISTS street VARCHAR(100);
ALTER TABLE company ADD COLUMN IF NOT EXISTS number VARCHAR(15);
ALTER TABLE company ADD COLUMN IF NOT EXISTS postal_code VARCHAR(8);
ALTER TABLE company ADD COLUMN IF NOT EXISTS complement VARCHAR(200);
ALTER TABLE company ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(100);
ALTER TABLE company ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE company ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE company ADD COLUMN IF NOT EXISTS id_city VARCHAR(36);